packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: false
  sharp: false
  unrs-resolver: false
peerDependencyRules:
  allowedVersions:
    typescript: 6.x
overrides:
  picomatch@<2.3.2: 2.3.2
  picomatch@>=4.0.0 <4.0.4: 4.0.4
  ajv@<8.18.0: 8.18.0
  postcss@<8.5.10: 8.5.10
  esbuild@<=0.24.2: 0.25.0
