/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * PayPay Money Diary API
 * PayPay 家計簿アプリケーション API
 * OpenAPI spec version: 1.0.0
 */

export interface CategoryResponse {
  id: string;
  name: string;
  color: string;
  icon: string | null;
  displayOrder: number;
  isDefault: boolean;
  isOther: boolean;
  userId: string;
  hasRules: boolean;
  hasTransactions: boolean;
}
