/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PayPay Money Diary API
 * PayPay 家計簿アプリケーション API
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryWithSystem } from "./categoryWithSystem";

export interface CategoryListResponse {
  /** カテゴリ一覧 */
  data: CategoryWithSystem[];
}
