/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * PayPay Money Diary API
 * PayPay 家計簿アプリケーション API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateCategoryRequest {
  /**
   * カテゴリ名
   * @minLength 1
   * @maxLength 50
   */
  name: string;
  /**
   * 色コード (#RRGGBB)
   * @pattern ^#[0-9A-Fa-f]{6}$
   */
  color: string;
  /**
   * アイコン
   * @maxLength 50
   */
  icon?: string;
  /**
   * 表示順
   * @minimum 0
   */
  displayOrder?: number;
}
