/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PayPay Money Diary API
 * PayPay 家計簿アプリケーション API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBudgets200DataItem } from "./getBudgets200DataItem";

export type GetBudgets200 = {
  data: GetBudgets200DataItem[];
};
