/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * PayPay Money Diary API
 * PayPay 家計簿アプリケーション API
 * OpenAPI spec version: 1.0.0
 */
import type { GetCategories200DataItem } from "./getCategories200DataItem";

export type GetCategories200 = {
  data: GetCategories200DataItem[];
};
