/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * PayPay Money Diary API
 * PayPay 家計簿アプリケーション API
 * OpenAPI spec version: 1.0.0
 */

export type GetTransactionsSortBy = (typeof GetTransactionsSortBy)[keyof typeof GetTransactionsSortBy];

export const GetTransactionsSortBy = {
  date: "date",
  amount: "amount",
} as const;
