/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * PayPay Money Diary API
 * PayPay 家計簿アプリケーション API
 * OpenAPI spec version: 1.0.0
 */
import type { GetTransactionsSortBy } from "./getTransactionsSortBy";
import type { GetTransactionsSortOrder } from "./getTransactionsSortOrder";

export type GetTransactionsParams = {
  year?: string;
  month?: string;
  categoryId?: string;
  search?: string;
  page?: string;
  limit?: string;
  sortBy?: GetTransactionsSortBy;
  sortOrder?: GetTransactionsSortOrder;
};
