/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * PayPay Money Diary API
 * PayPay 家計簿アプリケーション API
 * OpenAPI spec version: 1.0.0
 */

export type GetTransactionsSortBy = (typeof GetTransactionsSortBy)[keyof typeof GetTransactionsSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetTransactionsSortBy = {
  date: "date",
  amount: "amount",
} as const;
