/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * PayPay Money Diary API
 * PayPay 家計簿アプリケーション API
 * OpenAPI spec version: 1.0.0
 */
import type { GetTransactions200DataItem } from "./getTransactions200DataItem";
import type { GetTransactions200Pagination } from "./getTransactions200Pagination";

export type GetTransactions200 = {
  data: GetTransactions200DataItem[];
  pagination: GetTransactions200Pagination;
};
