/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * PayPay Money Diary API
 * PayPay 家計簿アプリケーション API
 * OpenAPI spec version: 1.0.0
 */
import type { GetTransactionsSummary200CategoryBreakdownItem } from "./getTransactionsSummary200CategoryBreakdownItem";
import type { GetTransactionsSummary200MonthlyBreakdownItem } from "./getTransactionsSummary200MonthlyBreakdownItem";
import type { GetTransactionsSummary200Summary } from "./getTransactionsSummary200Summary";

export type GetTransactionsSummary200 = {
  summary: GetTransactionsSummary200Summary;
  categoryBreakdown: GetTransactionsSummary200CategoryBreakdownItem[];
  monthlyBreakdown?: GetTransactionsSummary200MonthlyBreakdownItem[];
};
