/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * PayPay Money Diary API
 * PayPay 家計簿アプリケーション API
 * OpenAPI spec version: 1.0.0
 */
import type { GetTransactionsSummary200MonthlyBreakdownItemCategoriesItem } from "./getTransactionsSummary200MonthlyBreakdownItemCategoriesItem";

export type GetTransactionsSummary200MonthlyBreakdownItem = {
  month: number;
  totalAmount: number;
  categories: GetTransactionsSummary200MonthlyBreakdownItemCategoriesItem[];
};
