/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * PayPay Money Diary API
 * PayPay 家計簿アプリケーション API
 * OpenAPI spec version: 1.0.0
 */
import type { GetTransactions200Pagination } from './getTransactions200Pagination';
import type { TransactionResponse } from './transactionResponse';

export type GetTransactions200 = {
  data: TransactionResponse[];
  pagination: GetTransactions200Pagination;
};
