/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * PayPay Money Diary API
 * PayPay 家計簿アプリケーション API
 * OpenAPI spec version: 1.0.0
 */

export type PostTransactionsReCategorizeBody = {
  /**
   * @minimum 2000
   * @maximum 2100
   */
  year: number;
  /**
   * @minimum 1
   * @maximum 12
   */
  month?: number;
};
