/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * PayPay Money Diary API
 * PayPay 家計簿アプリケーション API
 * OpenAPI spec version: 1.0.0
 */

export type PostCategoriesBody = {
  /** @minLength 1 */
  name: string;
  /** @pattern ^#[0-9A-Fa-f]{6}$ */
  color: string;
  /** @nullable */
  icon?: string | null;
  displayOrder?: number;
};
