/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * PayPay Money Diary API
 * PayPay 家計簿アプリケーション API
 * OpenAPI spec version: 1.0.0
 */

export type PutTransactionsIdBody = {
  categoryId?: string;
  date?: string;
  amount?: number;
  /** @minLength 1 */
  description?: string;
};
