/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * PayPay Money Diary API
 * PayPay 家計簿アプリケーション API
 * OpenAPI spec version: 1.0.0
 */

export type PutTransactionsId200 = {
  id: string;
  userId: string;
  date: string;
  description: string;
  amount: number;
  /** @nullable */
  categoryId: string | null;
  categoryName: string;
  categoryColor: string;
  displayOrder: number;
  /** @nullable */
  paymentMethod?: string | null;
  createdAt: string;
  updatedAt: string;
};
