/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * PayPay Money Diary API
 * PayPay 家計簿アプリケーション API
 * OpenAPI spec version: 1.0.0
 */

export interface ReCategorizeInput {
  /**
   * @minimum 2000
   * @maximum 2100
   */
  year?: number;
  /**
   * @minimum 1
   * @maximum 12
   */
  month?: number;
}
