/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PayPay Money Diary API
 * PayPay 家計簿アプリケーション API
 * OpenAPI spec version: 1.0.0
 */

export interface Rule {
  /** ルールID */
  id: string;
  /** キーワード */
  keyword: string;
  /** カテゴリID */
  categoryId: string;
  /** カテゴリ名 */
  categoryName: string;
  /** 優先度 */
  priority: number;
  /** システムルールか */
  isSystem: boolean;
}
