/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * PayPay Money Diary API
 * PayPay 家計簿アプリケーション API
 * OpenAPI spec version: 1.0.0
 */

export interface RuleResponse {
  id: string;
  userId: string | null;
  keyword: string;
  categoryId: string;
  categoryName: string | null;
  priority: number;
  isSystem: boolean;
  createdAt: string;
  updatedAt: string;
}
