/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * PayPay Money Diary API
 * PayPay 家計簿アプリケーション API
 * OpenAPI spec version: 1.0.0
 */
import type { TransactionSummaryMonthlyBreakdownItemCategoriesItem } from "./transactionSummaryMonthlyBreakdownItemCategoriesItem";

export type TransactionSummaryMonthlyBreakdownItem = {
  month: number;
  totalAmount: number;
  categories: TransactionSummaryMonthlyBreakdownItemCategoriesItem[];
};
