/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * PayPay Money Diary API
 * PayPay 家計簿アプリケーション API
 * OpenAPI spec version: 1.0.0
 */

export interface Transaction {
  /** 取引ID */
  id: string;
  /** 取引日 */
  transactionDate: string;
  /** 金額 */
  amount: number;
  /** 取引先 */
  merchant: string;
  /**
   * 支払い方法
   * @nullable
   */
  paymentMethod: string | null;
  /**
   * カテゴリID
   * @nullable
   */
  categoryId: string | null;
  /**
   * カテゴリ名
   * @nullable
   */
  categoryName: string | null;
  /**
   * カテゴリ色
   * @nullable
   */
  categoryColor: string | null;
}
