/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * PayPay Money Diary API
 * PayPay 家計簿アプリケーション API
 * OpenAPI spec version: 1.0.0
 */
import type { TransactionSummaryCategoryBreakdownItem } from './transactionSummaryCategoryBreakdownItem';
import type { TransactionSummaryMonthlyBreakdownItem } from './transactionSummaryMonthlyBreakdownItem';
import type { TransactionSummarySummary } from './transactionSummarySummary';

export interface TransactionSummary {
  summary: TransactionSummarySummary;
  /** @maxItems 100 */
  categoryBreakdown: TransactionSummaryCategoryBreakdownItem[];
  /** @maxItems 12 */
  monthlyBreakdown?: TransactionSummaryMonthlyBreakdownItem[];
}
