/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * PayPay Money Diary API
 * PayPay 家計簿アプリケーション API
 * OpenAPI spec version: 1.0.0
 */
import type { TransactionSummaryMonthlyBreakdownItemCategoriesItem } from './transactionSummaryMonthlyBreakdownItemCategoriesItem';

export type TransactionSummaryMonthlyBreakdownItem = {
  month: number;
  totalAmount: number;
  /** @maxItems 100 */
  categories: TransactionSummaryMonthlyBreakdownItemCategoriesItem[];
};
