/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PayPay Money Diary API
 * PayPay 家計簿アプリケーション API
 * OpenAPI spec version: 1.0.0
 */
import type { Transaction } from "./transaction";
import type { Pagination } from "./pagination";

export interface TransactionListResponse {
  /** 取引一覧 */
  data: Transaction[];
  pagination: Pagination;
}
