/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * PayPay Money Diary API
 * PayPay 家計簿アプリケーション API
 * OpenAPI spec version: 1.0.0
 */

export type TransactionSummaryCategoryBreakdownItem = {
  categoryId: string | null;
  categoryName: string;
  categoryColor: string;
  displayOrder: number;
  totalAmount: number;
  transactionCount: number;
};
