/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * PayPay Money Diary API
 * PayPay 家計簿アプリケーション API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateRuleRequest {
  /**
   * キーワード
   * @minLength 1
   * @maxLength 100
   */
  keyword?: string;
  /** カテゴリID */
  categoryId?: string;
  /**
   * 優先度
   * @minimum 0
   */
  priority?: number;
}
