/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * PayPay Money Diary API
 * PayPay 家計簿アプリケーション API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateCategoryRequest {
  /**
   * カテゴリ名
   * @minLength 1
   * @maxLength 50
   */
  name?: string;
  /**
   * 色コード
   * @pattern ^#[0-9A-Fa-f]{6}$
   */
  color?: string;
  /**
   * アイコン
   * @maxLength 50
   * @nullable
   */
  icon?: string | null;
  /**
   * 表示順
   * @minimum 0
   */
  displayOrder?: number;
}
