/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * PayPay Money Diary API
 * PayPay 家計簿アプリケーション API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateTransactionInput {
  categoryId?: string;
  amount?: number;
  /** @minLength 1 */
  description?: string;
  date?: string;
}
