/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * PayPay Money Diary API
 * PayPay 家計簿アプリケーション API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateRuleInput {
  /** @minLength 1 */
  keyword?: string;
  categoryId?: string;
  /** @minimum 0 */
  priority?: number;
}
