/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * PayPay Money Diary API
 * PayPay 家計簿アプリケーション API
 * OpenAPI spec version: 1.0.0
 */

export interface UploadCsvResponse {
  /** メッセージ */
  message: string;
  /** アップロードID */
  uploadId: string;
  /** 総行数 */
  totalRows: number;
  /** インポート行数 */
  importedRows: number;
  /** スキップ行数 */
  skippedRows: number;
  /** 重複行数 */
  duplicateRows: number;
}
